Repository MozillaSecurity/FuzzManager, pull requests merged in 2021-08, with the labels that each got.

#770 Add multi-sort on all Vue tables.
  server/frontend/src/components/Crashes/List.vue
  server/frontend/src/components/Pools/List.vue
  server/frontend/src/components/Pools/View.vue
  server/frontend/src/components/Signatures/List.vue
  server/frontend/src/helpers.js
Labels: enhancement, crashmanager, taskmanager

#775 Update old task runs.
  server/taskmanager/cron.py
Labels: taskmanager

#778 Add a button to duplicate an existing BugzillaTemplate
  server/crashmanager/templates/bugzilla/list.html
  server/crashmanager/tests/test_bugs.py
  server/crashmanager/urls.py
  server/crashmanager/views.py
Labels: Teklia

#777 Display spinner when loading entries on crash and signature list
  server/frontend/package-lock.json
  server/frontend/package.json
  server/frontend/src/components/Crashes/List.vue
  server/frontend/src/components/Signatures/List.vue
Labels: Teklia

#781 Display creation date on notifications inbox
  server/crashmanager/serializers.py
  server/crashmanager/tests/test_inbox_rest.py
  server/frontend/src/components/Notifications/BucketHit.vue
  server/frontend/src/components/Notifications/InaccessibleBug.vue
Labels: enhancement, Teklia, live-server

#783 Add help popovers for substitution fields when publishing Bugzilla Bug/Comment
  server/frontend/package-lock.json
  server/frontend/package.json
  server/frontend/src/components/Bugs/Comments/PublicationForm.vue
  server/frontend/src/components/Bugs/HelpPopover.vue
  server/frontend/src/components/Bugs/PublicationForm.vue
  server/frontend/src/main.js
Labels: enhancement, bugzilla, Teklia

#779 Add query button instead of auto-submitting.
  server/frontend/src/components/Crashes/List.vue
  server/frontend/src/components/Signatures/List.vue
Labels: crashmanager
