Repository MozillaSecurity/FuzzManager, pull requests merged in 2021-05, with the labels that each got.

#654 Use TextField instead of Charfield with oversized max_length
  server/ec2spotmanager/migrations/0001_squashed_0013_add_gce_fields.py
  server/ec2spotmanager/models.py
Labels: Teklia

#657 Fix failing tests due to Django 2.2.21
  server/covmanager/tests/conftest.py
Labels: Teklia, bug

#655 Refactor Signature Creation/Edition form to a Vue component
  server/crashmanager/models.py
  server/crashmanager/serializers.py
  server/crashmanager/templates/layouts/layout_base.html
  server/crashmanager/templates/signatures/edit.html
  server/crashmanager/tests/test_signatures.py
  server/crashmanager/tests/test_signatures_rest.py
  server/crashmanager/views.py
  server/frontend/package-lock.json
  server/frontend/package.json
  server/frontend/src/api.js
  server/frontend/src/components/Signatures/CrashEntries/List.vue
  server/frontend/src/components/Signatures/CreateOrEdit.vue
  server/frontend/src/helpers.js
  server/frontend/src/main.js
  server/frontend/webpack.common.js
  server/server/settings.py
Labels: Teklia

#664 Remove support for Python 3.5
  .taskcluster.yml
  setup.cfg
  tox.ini
Labels: Teklia

#674 [FTB] Support UBSan messages in AutoRunner
  FTB/Running/AutoRunner.py
Labels: FTB, enhancement

#673 Fix an inconsistent behavior on watched buckets filtering
  server/crashmanager/views.py
Labels: Teklia

#662 Refactor the crash list to a Single File Component
  server/crashmanager/serializers.py
  server/crashmanager/templates/crashes/index.html
  server/crashmanager/templates/layouts/layout_base.html
  server/crashmanager/templates/signatures/try.html
  server/crashmanager/templates/signatures/view.html
  server/crashmanager/tests/test_crashes.py
  server/crashmanager/tests/test_signatures.py
  server/crashmanager/urls.py
  server/crashmanager/views.py
  server/frontend/package-lock.json
  server/frontend/package.json
  server/frontend/src/api.js
  server/frontend/src/components/Crashes/List.vue
  server/frontend/src/components/Crashes/Row.vue
  server/frontend/src/components/Signatures/CrashEntries/List.vue
  server/frontend/src/helpers.js
  server/frontend/src/main.js
  server/frontend/src/router.js
  server/frontend/webpack.common.js
Labels: Teklia

#679 Add a component to add/edit/remove a Provider API key in localStorage
  server/crashmanager/templates/usersettings.html
  server/crashmanager/views.py
  server/frontend/src/api.js
  server/frontend/src/bugzilla_api.js
  server/frontend/src/components/ProviderKey.vue
  server/frontend/src/main.js
Labels: Teklia

#685 Update fixture to fix unit test using fuzzing-decision Pool parser
  server/taskmanager/tests/fixtures/pool1/pool1.yml
Labels: Teklia

#684 Manage Bugzilla templates through Django forms
  server/crashmanager/Bugtracker/BugzillaProvider.py
  server/crashmanager/Bugtracker/Provider.py
  server/crashmanager/forms.py
  server/crashmanager/migrations/0004_bugzillatemplate_mode.py
  server/crashmanager/models.py
  server/crashmanager/serializers.py
  server/crashmanager/templates/bugzilla/create_edit.html
  server/crashmanager/templates/bugzilla/delete.html
  server/crashmanager/templates/bugzilla/form.html
  server/crashmanager/templates/bugzilla/list.html
  server/crashmanager/templates/bugzilla/submit.html
  server/crashmanager/templates/bugzilla/view_edit_template.html
  server/crashmanager/templates/shared/header.html
  server/crashmanager/tests/conftest.py
  server/crashmanager/tests/test_bugs.py
  server/crashmanager/tests/test_templates_rest.py
  server/crashmanager/urls.py
  server/crashmanager/views.py
  server/requirements.txt
  server/requirements3.0.txt
  server/server/settings.py
Labels: Teklia

#687 Use v-pre to prevent Vue.js failure on special characters
  server/crashmanager/templates/crashes/view.html
  server/crashmanager/templates/signatures/optimize.html
  server/crashmanager/templates/signatures/try.html
  server/crashmanager/templates/signatures/view.html
Labels: Teklia
